### ISSUE TITLE
cannot load pubkey of a specific email

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#484] opened 2019-03-18 22:02 UTC
When I enter `datan.domonkos@gmail.com` in public key search (or as recipient) it doesn't find pubkey. But we actually have one: https://flowcrypt.com/pub/datan.domonkos@gmail.com

**Comment by DenBond7** [comment] 2019-03-19 10:52
Duplicate of #473

**Closed** 2019-03-19 10:52 UTC

**Comment by DenBond7** [comment] 2019-03-19 10:56
#473 and #484 have the same problem

**Comment by tomholub** [comment] 2019-03-19 12:23
Got it
