### ISSUE TITLE
test: setup app -> change password on Google -> open app again

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#207] opened 2018-02-11 08:08 UTC
Try this scenario. This will most likely cause trouble, because Google requires that oAuth apps are connected again - I think.

**Comment by DenBond7** [comment] 2018-02-12 13:53
for me
ref https://mail.google.com/mail/u/0/#inbox/161878cd21fee04e

```
[STACK_TRACE]
java.lang.Exception: EmailSyncService.onError
        at com.flowcrypt.email.service.EmailSyncService.onError(EmailSyncService.java:434)
        at com.flowcrypt.email.api.email.sync.tasks.BaseSyncTask.handleException(BaseSyncTask.java:76)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessagesToCacheSyncTask.handleException(LoadMessagesToCacheSyncTask.java:32)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:518)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:593)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: com.google.android.gms.auth.UserRecoverableAuthException: NeedPermission
        at com.google.android.gms.auth.zze.zzac(Unknown Source:103)
        at com.google.android.gms.auth.zzd.zza(Unknown Source:21)
        at com.google.android.gms.auth.zzd.zzb(Unknown Source:67)
        at com.google.android.gms.auth.zzd.getToken(Unknown Source:3)
        at com.google.android.gms.auth.zzd.getToken(Unknown Source:5)
        at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source:0)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:78)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:173)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:465)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:494)
        ... 6 more
com.google.android.gms.auth.UserRecoverableAuthException: NeedPermission
        at com.google.android.gms.auth.zze.zzac(Unknown Source:103)
        at com.google.android.gms.auth.zzd.zza(Unknown Source:21)
        at com.google.android.gms.auth.zzd.zzb(Unknown Source:67)
        at com.google.android.gms.auth.zzd.getToken(Unknown Source:3)
        at com.google.android.gms.auth.zzd.getToken(Unknown Source:5)
        at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source:0)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:78)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:173)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:465)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:494)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:593)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by DenBond7** [comment] 2018-02-28 14:23
I'm moving this issue to 0.6.1. Because we have received a lot of ACRA reports about this problem.

**Comment by DenBond7** [comment] 2018-02-28 14:41
This situation for the user looks like below

![screenshot_1519828736](https://user-images.githubusercontent.com/2863246/36793387-f84a314e-1ca5-11e8-8dbc-edcb2d2609d2.png)

To reproduce it we can go to https://myaccount.google.com/u/0/permissions and decline an access to the Google account.

**Comment by tomholub** [comment] 2018-03-01 02:13
You can say 
```
Cannot open inbox. Did you recently change email security settings?

[Re-connect]
```

I guess if it's IMAP, the re-connect button would take user to imap setup page, else to oauth screen.

**Closed** 2018-03-02 08:34 UTC
