### ISSUE TITLE
Delete emails from inbox don't stay deleted

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1144] opened 2021-04-01 20:43 UTC
How to reproduce:

1. Delete an email from your inbox (encrypted or unencrypted, it doesn't matter)
2. The email disappears
3. Swipe to refresh the inbox
4. The email is back!

Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtGrPSXrhSsgbtlwKvwmVVFDz
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtGldXhFLBQwQhCpbQWfqPzdL

I was able to reproduce this issue on my own phone with Android installed.

**Comment by DenBond7** [comment] 2021-04-02 04:12
Thank you for reporting. It's a duplicate of #1135.

**Closed by DenBond7** 2021-04-02 04:12 UTC
Labels: bug, user experience

**Comment by seisvelas** [comment] 2021-04-02 05:06
Woah, sorry I didn't check to see whether there was already an issue. My bad!
