### ISSUE TITLE
Error with Attachment Parsing - Unexpected Character in Filename

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-android#2425] opened 2023-08-18 06:36 UTC
Encountered an issue while linking my FlowCrypt account to the Android app.
When viewing the inbox list screen, below error appears.

Error details:

```
In parameter list <; filename="what"s_up.txt.pgp>, expected '";', got "s_up.txt.pgp"
```
![Screenshot_10](https://github.com/FlowCrypt/flowcrypt-android/assets/77344191/c5cf6de1-363b-4ed9-bfc4-c549f2823c63)

It seems related to an email that has an attachment which is named with special characters like "what's_up?.txt."
If I delete that email, app works fine.

Additionally, I believe the thread list should still be displayed, even if the app can't render some threads for whatever reason. This current behavior might disrupt the user experience.

**Comment by ioanmo226** [comment] 2023-08-18 06:36
@DenBond7

**Comment by DenBond7** [comment] 2023-08-18 06:57
@ioanmo226 Can you share that message? or make the similar to reproduce the bug?

**Comment by ioanmo226** [comment] 2023-08-18 07:05
I accidentaly deleted that message(To see correct functionalitities of Android app). Let me reproduce it.

**Comment by ioanmo226** [comment] 2023-08-18 07:25
@DenBond7 Just sent you sample email.
FYI it can't be generated with current browser extension version as this issue was addressed a while ago.

**Comment by DenBond7** [comment] 2023-08-18 07:38
I've checked the received message. It has a little different info. Anyway, I have enough information to reproduce the bug. I think I know how to recreate such a message manually. Thank you!

**Comment by DenBond7** [comment] 2023-08-24 11:24
ref https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http

**Comment by DenBond7** [comment] 2023-08-24 11:25
I'm moving it to later. unfortunately, I can't reproduce this bug. I will wait for more details from other sources.

**Comment by ioanmo226** [comment] 2023-08-24 15:17
OK

**Comment by DenBond7** [comment] 2023-08-28 10:33
```
jakarta.mail.internet.ParseException: In parameter list
                                                                                                    <; filename="what"s_up.txt.pgp">, expected ';', got "s_up.txt.pgp"
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at jakarta.mail.internet.ParameterList.<init>(ParameterList.java:290)
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at
                                                                                                    jakarta.mail.internet.ContentDisposition.<init>(ContentDisposition.java:85)
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at
                                                                                                    jakarta.mail.internet.MimeBodyPart.getDisposition(MimeBodyPart.java:1210)
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at jakarta.mail.internet.MimeBodyPart.getDisposition(MimeBodyPart.java:303)
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at
                                                                                                    com.flowcrypt.email.api.email.EmailUtil$Companion.isPartAllowed(EmailUtil.kt:919)
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at
                                                                                                    com.flowcrypt.email.api.email.gmail.api.GmaiAPIMimeMessage.parseBodyPart(GmaiAPIMimeMessage.kt:93)
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at
                                                                                                    com.flowcrypt.email.api.email.gmail.api.GmaiAPIMimeMessage.generateMultipart(GmaiAPIMimeMessage.kt:79)
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at
                                                                                                    com.flowcrypt.email.api.email.gmail.api.GmaiAPIMimeMessage.<init>(GmaiAPIMimeMessage.kt:46)
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at
                                                                                                    com.flowcrypt.email.api.email.gmail.api.GmaiAPIMimeMessage.<init>(GmaiAPIMimeMessage.kt:34)
2023-08-28 13:30:42.574 11445-13044 System.err              com.flowcrypt.email.debug            W  	at
```

**Closed** 2023-08-29 06:27 UTC
Labels: bug
