### ISSUE TITLE
The SENT folder is not defined

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#467] opened 2019-03-05 11:30 UTC
```
[SUMMARY]
java.lang.IllegalArgumentException: The SENT folder is not defined
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:31)
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.sendQueuedMsgs(MessagesSenderJobService.java:278)
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.doInBackground(MessagesSenderJobService.java:182)
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.doInBackground(MessagesSenderJobService.java:144)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: The SENT folder is not defined
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.saveCopyOfSentMsg(MessagesSenderJobService.java:542)
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.sendMsg(MessagesSenderJobService.java:435)
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.sendQueuedMsgs(MessagesSenderJobService.java:258)
        ... 8 more
java.lang.IllegalArgumentException: The SENT folder is not defined
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.saveCopyOfSentMsg(MessagesSenderJobService.java:542)
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.sendMsg(MessagesSenderJobService.java:435)
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.sendQueuedMsgs(MessagesSenderJobService.java:258)
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.doInBackground(MessagesSenderJobService.java:182)
        at com.flowcrypt.email.jobscheduler.MessagesSenderJobService$SendMessagesAsyncTask.doInBackground(MessagesSenderJobService.java:144)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#search/label%3Awork-flowcrypt-crashes+label%3Aunread/FMfcgxwBVgnzKZMpzWXNBCfhlGbBdmJJ

**Comment by DenBond7** [comment] 2019-04-11 10:11
I'm moving it to `later` (need more details from users)

**Comment by tomholub** [comment] 2019-04-11 11:23
Sometimes users complain that encrypted messages don't get stored in sent folder, but plain messages do.

**Comment by tomholub** [comment] 2019-04-11 11:23
```
*****Next, if I send encrypted mail, there is no record of it in my
sent folder even though flowcrypt has sent it encrypted to both keys.
If I sent unencrypted, then I have a copy in my sent folder.
```

**Comment by DenBond7** [comment] 2019-04-11 12:15
It would be great to know what a provider is used. I've added debug code for that.

**Comment by tomholub** [comment] 2021-04-21 06:41
closing as cannot reproduce

**Closed by tomholub** 2021-04-21 06:41 UTC
Labels: bug
