### ISSUE TITLE
cannot receive email notification for newly received email

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2141] opened 2023-01-10 08:23 UTC
We received a concern from a user stating that they cannot receive an email notification for newly received emails, but only if the app is not open/running in the background. I experienced the same thing during my testing.

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGrbvBnSgfjHJjwkSPzHSjmFZDz
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGslbJgczmxQLgkhmpDzgpLLVCL

**Comment by DenBond7** [comment] 2023-01-10 08:37
@martgil Please add more details to reproduce it.

**Comment by martgil** [comment] 2023-01-10 08:47
Ah yes. To test it out, send an encrypted email to your test account configured in your device with FlowCrypt installed but not open. If the android device has Gmail, noticed that you will get a notification from it, but not from FlowCrypt. You will only get a notification from FlowCrypt when you open the app and leave it running in the background (re-send a test email).

**Comment by DenBond7** [comment] 2023-01-10 08:49
`Enterprise` or `Consumer` version?

**Comment by martgil** [comment] 2023-01-10 09:14
For me, `consumer` (browser extension) -> `consumer` (android) ->  works -- but on some other test, it takes time but not horribly long enough though notification from Gmail is almost instant. But `enterprise` (browser extension) -> `consumer`(android) didn't work all through out the test.

**Comment by DenBond7** [comment] 2023-01-10 09:19
Got it. I will check. One more question. Are we talking about only encrypted messages or about all?

**Comment by martgil** [comment] 2023-01-10 10:36
it's about all messages. Though I noticed that when it's a while the app is not connected to the wifi and then reconnects. The first batch of emails will arrive but then after that, the app's notification will become inconsistent again vs Gmail consistently showing notification for every new email.

**Comment by DenBond7** [comment] 2023-04-05 05:45
@sosnovsky To receive real-time updates we can use [Push Notifications](https://developers.google.com/gmail/api/guides/push).
But for that, we need to add some changes in the Google Developer Console(based on the [gide](https://developers.google.com/gmail/api/guides/push)). I can add that changes myself(I need access to the project) or somebody can help me do that. @tomholub ping you just in case.

@sosnovsky by the way, do we use real-time notifications about new messages for `iOS`?

**Comment by sosnovsky** [comment] 2023-04-05 07:02
> @sosnovsky by the way, do we use real-time notifications about new messages for iOS?

No, iOS app doesn't support push notifications for now.

> @sosnovsky To receive real-time updates we can use [Push Notifications](https://developers.google.com/gmail/api/guides/push).

Sounds good, but I don't have access to Google dev console too.
By the way, as I understood Android has some notifications functionality implemented, but it works only when app is in background? Is it using some API polling to check for new mails?

**Comment by DenBond7** [comment] 2023-04-05 07:08
> By the way, as I understood Android has some notifications functionality implemented, but it works only when app is in background?

yup, Android checks for updates no more than once per 15 minutes

> Is it using some API polling to check for new mails?

we use https://developers.google.com/gmail/api/reference/rest/v1/users.history

**Comment by DenBond7** [comment] 2023-04-05 07:09
> Sounds good, but I don't have access to Google dev console too.

@tomholub it seems we need your help :)

**Comment by DenBond7** [comment] 2023-04-05 16:53
@tomholub ping you just in case. It's blocking me a little.I've checked I have access to the developer console, but I don't have a permission to make changes.

**Comment by DenBond7** [comment] 2023-04-12 10:20
After some research, I see the following ways how to improve notifications(I'm posting it just for history)

1. Use the Android Gmail App content provider. [The Gmail Public Labels API](https://android-developers.googleblog.com/2012/04/gmail-public-labels-api.html), [GmailContract] (https://developers.google.com/gmail/android/com/google/android/gm/contentprovider/GmailContract). It allows `Android FlowCrypt` to listen for updates in `Android Gmail App`. As `Android Gmail App` works well and receives almost real-time updates about new messages we will be able to notify users about updates almost as `Android Gmail App` does it(with a few seconds delay). 

**pros:**

- we resolve the issue
- implementation is not difficult

**cons**

- implementation is deprecated. It uses old approaches.
- a user should have `Android Gmail App` installed before `Android FlowCrypt` will be installed
- can be used only for Android

2. Use [Cloud Pub/Sub](https://developers.google.com/gmail/api/guides/push#initial_cloud_pubsub_setup) directly. Based on [Pub/Sub on Android via Google Sign-in](https://stackoverflow.com/questions/75983750/pub-sub-on-android-via-google-sign-in) it's not a good idea at all. I've found a way how to make it work. But it's not a secure way.

3. Based on [Pub/Sub on Android via Google Sign-in](https://stackoverflow.com/questions/75983750/pub-sub-on-android-via-google-sign-in) maybe it will be possible to use [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging) and [Pub/Sub triggers](https://firebase.google.com/docs/functions/pubsub-events). I'm going to investigate this way.

**Comment by DenBond7** [comment] 2023-04-17 08:50
After some research and testing, I have the following result:

1. To be able to receive faster updates about messages(new, update, and so on) on Android we have to use push notifications. It's only one way for now to work effectively.  All other cases tasted on my side or have bad(unsafe) approaches or don't work well due to different reasons(it depends on a particular device or Android behavior at all)
2. @martgil So for now we have the same situation: on Android, updates can be fetched once per 15 minutes or less automatically. If a user need to have the latest info he has to do `pull-to-refresh` manually.
3. @sosnovsky I don't know how you are going to integrate real-time notifications about updates on iOS. If you can use [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging) maybe we can have only one backend solution for both platforms.  For now, without a backend solution, I can't show updates faster. @sosnovsky @tomholub Please let me know if we are interested in it and I will create a new issue where we can discuss it.

**Comment by sosnovsky** [comment] 2023-04-17 13:20
Having push-notifications is a needed functionality, especially for email client. But implementation seems to be quite complicated, as it will need additional configurations for customer and enterprise apps, adding Firebase dependency, plus some backend work.

I'm not sure if it's our priority for now, @tomholub what do you think?

**Comment by tomholub** [comment] 2023-04-17 13:30
not now, but we can discuss it. then schedule for later

**Comment by DenBond7** [comment] 2023-04-17 13:40
In that case, @martgil I close the current issue. #2289 will resolve the notification problem for Gmail API.

**Closed by DenBond7** 2023-04-17 13:40 UTC
