### ISSUE TITLE
Messages loading forever

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#986] opened 2020-11-09 06:12 UTC
>Is there some sync the first time flow crypt is launched on android? Just getting a timer for the first hour.

Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjKpnlTdnMSPLMqWsBpGTxHpg
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjKngLsrtFVLWJCjjLFBgvdfl

Followup from one of the users reporting this issue:

> I gave up and started from scratch
> 
> I have reinstalled the chrome browser extension on my laptop and imported the key that was found.
> There are no errors.
> I can send and receive encrypted email with gmail.
> 
> I have installed the android app and imported the same key
> however i just get a spinning circle
> 
> under settings, backup - error : could not retrieve your private key
> if i click on keys and import private key it tells me the key is already installed which is what I would expect
> attester is ok. 
> 
> any advice?

I can't reproduce this on my own phone

**Comment by DenBond7** [comment] 2020-11-09 07:00
@seisvelas 
 > I can't reproduce this on my own phone

Because that's an unexpected error. I think a user has some problems on his side. I need to know more details to help. Could you add me to the conversation?

**Comment by seisvelas** [comment] 2020-11-09 07:06
>Could you add me to the conversation?

Done!

**Comment by DenBond7** [comment] 2020-11-09 11:44
I'm closing this issue. The user can't use the app because IMAP access is disabled. I've created a separate issue to add checking of IMAP access for GMail users.

**Closed by DenBond7** 2020-11-09 11:44 UTC
Labels: bug
