### ISSUE TITLE
Migration to PGPainless. Message details. "signed message that looks like encrypted"

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1462] opened 2021-09-20 08:24 UTC
web
![Selection_822](https://user-images.githubusercontent.com/2863246/133974206-8ae59d56-f19e-46be-aba3-b9fd9b7b33ce.png)

Android Node.js
![Selection_823](https://user-images.githubusercontent.com/2863246/133974248-507e90eb-6320-4ae9-9f04-292ec2f068fe.png)

Android PGPainless(kotlin)

![Selection_824](https://user-images.githubusercontent.com/2863246/133974340-675b8f37-f02b-4b41-a58f-d7cbe4b069ef.png)

**Comment by tomholub** [comment] 2021-09-20 11:23
this is a duplicate of https://github.com/FlowCrypt/flowcrypt-android/issues/1459 just a different test message, I think.

**Closed by tomholub** 2021-09-20 11:23 UTC
