### ISSUE TITLE
Semaphore fails: NDK at /home/semaphore/Android/Sdk/ndk/22.0.7026061 did not have a source.properties file

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-android#1128] opened 2021-03-25 07:16 UTC
For example, in the #1125 
https://flowcrypt.semaphoreci.com/jobs/e9151626-290e-4052-a51d-c59240d332a1
Also here: #1126 and I think in some others

**Comment by DenBond7** [comment] 2021-04-05 16:34
I'm closing it. It was the Semaphore CI caching problem. Can't reproduce.

**Closed by DenBond7** 2021-04-05 16:34 UTC
Labels: android_testing
